"""Add status to empresa and update enums

Revision ID: 1dcc80d4086d
Revises: f5c89943e7eb
Create Date: 2026-08-19 16:51:43.508920

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1dcc80d4086d"
down_revision: str | Sequence[str] | None = "f5c89943e7eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "empresa",
        sa.Column(
            "status", sa.String(length=50), nullable=False, server_default="ativa"
        ),
    )
    # ### end Alembic commands ###
    op.execute("ALTER TYPE tipo_usuario_enum RENAME VALUE 'admin' TO 'admin_sistema'")
    op.execute("ALTER TYPE tipo_usuario_enum ADD VALUE IF NOT EXISTS 'admin_empresa'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("empresa", "status")
    # ### end Alembic commands ###
    op.execute("ALTER TYPE tipo_usuario_enum RENAME VALUE 'admin_sistema' TO 'admin'")
