"""adiciona cnpj ao recrutador

Revision ID: 52a533a1e485
Revises: 869ef0b06279
Create Date: 2026-08-02 19:01:27.095098

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52a533a1e485"
down_revision: str | Sequence[str] | None = "869ef0b06279"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recrutador", sa.Column("cnpj", sa.String(length=14), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recrutador", "cnpj")
    # ### end Alembic commands ###
