"""add_empresa_id_to_candidato

Revision ID: 5c72b0fe2188
Revises: 1dcc80d4086d
Create Date: 2026-08-19 19:36:12.285539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c72b0fe2188'
down_revision: Union[str, Sequence[str], None] = '1dcc80d4086d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidato', sa.Column('empresa_id', sa.UUID(), nullable=True))
    op.execute(
        "UPDATE candidato SET empresa_id = (SELECT id FROM empresa WHERE nome = 'Empresa Teste' LIMIT 1)"
    )
    op.alter_column('candidato', 'empresa_id', nullable=False)
    
    op.drop_index(op.f('ix_candidato_email'), table_name='candidato')
    op.create_index(op.f('ix_candidato_email'), 'candidato', ['email'], unique=False)
    op.create_unique_constraint('uq_candidato_email_empresa', 'candidato', ['email', 'empresa_id'])
    op.create_foreign_key(None, 'candidato', 'empresa', ['empresa_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidato', type_='foreignkey')
    op.drop_constraint('uq_candidato_email_empresa', 'candidato', type_='unique')
    op.drop_index(op.f('ix_candidato_email'), table_name='candidato')
    op.create_index(op.f('ix_candidato_email'), 'candidato', ['email'], unique=True)
    op.drop_column('candidato', 'empresa_id')
    # ### end Alembic commands ###
