"""add_fk_empresa_to_grupo_habilidade

Revision ID: 635a471d5da7
Revises: 5c72b0fe2188
Create Date: 2026-08-19 19:42:11.263017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635a471d5da7'
down_revision: Union[str, Sequence[str], None] = '5c72b0fe2188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'grupo_habilidade', 'empresa', ['empresa_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grupo_habilidade', type_='foreignkey')
    # ### end Alembic commands ###
