"""remove cpf do usuario

Revision ID: 6b81e2f33812
Revises: 52a533a1e485
Create Date: 2026-08-02 19:08:39.628860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b81e2f33812'
down_revision: Union[str, Sequence[str], None] = '52a533a1e485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('usuario_cpf_key'), 'usuario', type_='unique')
    op.drop_column('usuario', 'cpf')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('cpf', sa.VARCHAR(length=14), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('usuario_cpf_key'), 'usuario', ['cpf'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
