"""reset_schema

Revision ID: 869ef0b06279
Revises:
Create Date: 2026-07-25 23:20:37.644700

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "869ef0b06279"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidato",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("telefone", sa.String(length=50), nullable=True),
        sa.Column("curriculo_url", sa.Text(), nullable=True),
        sa.Column("resumo_profissional", sa.Text(), nullable=True),
        sa.Column(
            "experiencias", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "tecnologias", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_candidato_email"), "candidato", ["email"], unique=True)
    op.create_table(
        "usuario",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nome_completo", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("senha_hash", sa.String(length=255), nullable=False),
        sa.Column("telefone", sa.String(length=50), nullable=True),
        sa.Column("cpf", sa.String(length=14), nullable=True),
        sa.Column(
            "tipo_usuario",
            sa.Enum("recrutador", name="tipo_usuario_enum"),
            nullable=False,
        ),
        sa.Column(
            "data_criacao",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cpf"),
    )
    op.create_index(op.f("ix_usuario_email"), "usuario", ["email"], unique=True)
    op.create_table(
        "recrutador",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("empresa", sa.String(length=255), nullable=False),
        sa.Column("cargo", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["usuario.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vaga",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("recrutador_id", sa.UUID(), nullable=False),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column("descricao_candidato_ideal", sa.Text(), nullable=True),
        sa.Column(
            "requisitos_hard", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "requisitos_soft", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum("ativa", "pausada", "encerrada", name="status_vaga_enum"),
            nullable=False,
        ),
        sa.Column(
            "data_criacao",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["recrutador_id"], ["recrutador.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "candidatura",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vaga_id", sa.UUID(), nullable=False),
        sa.Column("candidato_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pendente",
                "em_entrevista",
                "avaliada",
                "aprovada",
                "rejeitada",
                name="status_candidatura_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "data_candidatura",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["candidato_id"], ["candidato.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vaga_id"], ["vaga.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vaga_id", "candidato_id", name="uq_vaga_candidato"),
    )
    op.create_table(
        "entrevista",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("candidatura_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "agendada",
                "em_andamento",
                "concluida",
                "cancelada",
                name="status_entrevista_enum",
            ),
            nullable=False,
        ),
        sa.Column("data_inicio", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data_fim", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score_geral", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("feedback_candidato", sa.Text(), nullable=True),
        sa.Column("feedback_recrutador", sa.Text(), nullable=True),
        sa.Column(
            "data_criacao",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidatura_id"], ["candidatura.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pergunta_entrevista",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entrevista_id", sa.UUID(), nullable=False),
        sa.Column("pergunta_texto", sa.Text(), nullable=False),
        sa.Column("ordem", sa.Integer(), nullable=False),
        sa.Column(
            "data_criacao",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entrevista_id"], ["entrevista.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entrevista_id", "ordem", name="uq_entrevista_ordem"),
    )
    op.create_table(
        "resposta_entrevista",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pergunta_id", sa.UUID(), nullable=False),
        sa.Column("audio_url", sa.Text(), nullable=True),
        sa.Column("transcricao", sa.Text(), nullable=True),
        sa.Column("metricas", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "data_resposta",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pergunta_id"], ["pergunta_entrevista.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pergunta_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resposta_entrevista")
    op.drop_table("pergunta_entrevista")
    op.drop_table("entrevista")
    op.drop_table("candidatura")
    op.drop_table("vaga")
    op.drop_table("recrutador")
    op.drop_index(op.f("ix_usuario_email"), table_name="usuario")
    op.drop_table("usuario")
    op.drop_index(op.f("ix_candidato_email"), table_name="candidato")
    op.drop_table("candidato")
    # ### end Alembic commands ###
